title: Sun God Festival 2019
email: asgraphicstudio@ucsd.edu
description: 04.27.2019 | 12PM â€“ 6PM | RIMAC
baseurl: "/sgf19" # the subpath of your site, e.g. /blog
base: "/sgf19/"
url: "http://sgf.dreamhosters.com/sgf19" # the base hostname & protocol for your site, e.g. http://example.com
github_username: emilynguyen

# Build settings
markdown: kramdown
plugins:
  - jekyll-autoprefixer
sass:
  sass_dir: _sass
include: ["_pages"]
kramdown:
  input: GFM
